### ISSUE TITLE
Can we add page breaks

### ISSUE THREAD

**Issue by sr2399** [dmk99/react-pdf-table#40]
Can we add  page breaks according to data consuming in the first page and remaining  pages at same page break

**Comment by dmk99** [comment]
Dynamically adding page breaks is not the easiest thing to implement especially because, to the best of my knowledge, react-pdf/renderer does not expose the bounding boxes of the elements.

A workaround for this would be to determine the number of rows you can fit into a single page and then split the array into multiple chunks. Then render each array chunk on it's own page.
